name: dump-event
on: pull_request_target

jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -vp objects/
          cat > objects/github.json <<'EOF'
          ${{ toJson(github) }}
          EOF

          cat > objects/env.json <<'EOF'
          ${{ toJson(env) }}
          EOF
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: renovate-report
          path: objects/
          retention-days: 1


