name: renovate

on:
  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset
      logLevel:
        description: 'Log level'
        type: choice
        default: info
        options:
          - debug
          - info
      autoApprove:
        description: 'Automatically approve Renovate PRs?'
        type: choice
        default: "true"
        options:
          - "true"
          - "false"
  schedule:
    - cron: 0 10 * * *

concurrency:
  group: >
    ${{ github.repository }}-
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && format( '{0}-{1}', github.run_id, github.sha ) || '' }}
  cancel-in-progress: true

env:
  RENOVATE_CACHE_ARCHIVE: /tmp/renovate-cache.tar.gz
  RENOVATE_REPORT_FILE: /tmp/renovate-report.json
  RENOVATE_CACHE_KEY: renovate-cache
  BUILDKIT_PROGRESS: plain

permissions:
  contents: read
  pull-requests: write # This is here so PR's can be approved.
  actions: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - uses: dawidd6/action-download-artifact@0bd50d53a6d7fb5cb921e607957e9cc12b4ce392 # v12
        if: github.event.inputs.repoCache != 'disabled'
        continue-on-error: true
        with:
          name: ${{ env.RENOVATE_CACHE_KEY }}
          path: /tmp
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run renovate
        run: |
          set -x -Eeuo pipefail
          exec task renovate
        env:
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.repoCache || 'enabled' }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_ACTIONS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}
          RENOVATE_AUTO_APPROVE: "${{ github.event.inputs.autoApprove || 'false' }}"

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: github.event.inputs.repoCache != 'disabled'
        with:
          name: ${{ env.RENOVATE_CACHE_KEY }}
          path: ${{ env.RENOVATE_CACHE_ARCHIVE }}
          retention-days: 1

      - name: Export Renovate report
        if: always()
        run: |
          set -x -Eeuo pipefail
          exec task renovate:report:export
        env:
          RENOVATE_REPORT_FILE: ${{ env.RENOVATE_REPORT_FILE }}

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: always()
        with:
          name: renovate-report
          path: ${{ env.RENOVATE_REPORT_FILE }}
          retention-days: 5
